Repository geotiffjs/geotiff.js, pull requests merged in 2025-06, with the labels that each got.

#426 geotiffimage: stop mentioning that readRGB() forces interleaving
  README.md
  src/geotiffimage.js
Labels: docs

#465 Workflow updates & release improvements
  .github/changelog.json
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/version.yml
Labels: ci

#467 Fix version.yml typo, validate version output
  .github/workflows/version.yml
Labels: ci, ci-ignore, bugfix
